'use client';
import { useEffect,useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { useParams,useRouter } from 'next/navigation';

export default function ImmoDetail(){const params=useParams<{id:string}>();const router=useRouter();const [item,setItem]=useState<any>(null);const [error,setError]=useState('');const [fav,setFav]=useState(false);const [busy,setBusy]=useState(false);const [contacting,setContacting]=useState(false);
 useEffect(()=>{void load()},[params.id]);
 async function load(){const r=await fetch(`/api/listings/${params.id}`,{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error||'Erreur');return}setItem(d.data); const s=createClient();const {data:{user}}=await s.auth.getUser();if(user){const f=await s.from('favorites').select('listing_id').eq('listing_id',params.id).maybeSingle();setFav(Boolean(f.data));}}
 async function toggle(){setBusy(true);const r=await fetch('/api/favorites',{method:fav?'DELETE':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({listingId:params.id})});if(r.ok)setFav(!fav);else{const d=await r.json();setError(d.error||'Connexion requise.')}setBusy(false)}
 async function contact(){setContacting(true);setError('');try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push(`/auth/sign-in?next=/immowin/${params.id}`);return;}if(!item.owner_id){setError('Le vendeur n’est pas disponible.');return;}const r=await fetch('/api/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipientId:item.owner_id,listingId:params.id,message:`Bonjour, je suis intéressé par votre annonce « ${item.title} ». Est-elle toujours disponible ?`})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Impossible de contacter le vendeur.');router.push(`/messages/${d.data.conversationId}`)}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{setContacting(false)}}
 async function close(){if(!confirm('Fermer cette annonce ?'))return;const r=await fetch(`/api/listings/${params.id}`,{method:'DELETE'});if(r.ok)router.push('/');else{const d=await r.json();setError(d.error||'Erreur')}}
 if(error&&!item)return <main className="wrap"><div className="notice error">{error}</div></main>;if(!item)return <main className="wrap"><div className="empty">Chargement…</div></main>;
 const images=item.listing_images??[];return <main className="wrap"><header className="header"><div><div className="brand">WinsWi · ImmoWin</div><div className="tag">Détail de l’annonce</div></div><div className="headerActions"><a className="btn secondary" href="/">Accueil</a><button className="btn secondary" onClick={toggle} disabled={busy}>{fav?'★ Retirer':'☆ Favori'}</button></div></header><article className="card detail"><div className="muted">{item.wilaya||item.location||'Algérie'} · {item.commune||''}</div><h1>{item.title}</h1><p>{item.description}</p>{item.price!=null&&<div className="price">{Number(item.price).toLocaleString('fr-DZ')} {item.currency||'DZD'}</div>}<div className="badges"><span className="badge">{item.metadata?.transaction||'annonce'}</span><span className="badge">{item.metadata?.propertyType||'immobilier'}</span>{item.verified&&<span className="badge">✓ Vérifié</span>}</div><div className="grid">{images.map((im:any)=><ImageCard key={im.id ?? im.storage_path} path={im.storage_path}/>)}</div><div className="actions"><button className="btn" onClick={contact} disabled={contacting}>{contacting?'Ouverture…':'Contacter le vendeur'}</button><a className="btn secondary" href="/immowin/nouvelle">Publier une annonce</a><button className="btn secondary" onClick={close}>Fermer l’annonce</button></div>{error&&<div className="notice error">{error}</div>}</article></main>}
function ImageCard({path}:{path:string}){const [url,setUrl]=useState('');useEffect(()=>{fetch('/api/storage/sign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})}).then(r=>r.json()).then(d=>{if(d.signedUrl)setUrl(d.signedUrl)}).catch(()=>{})},[path]);return url?<img className="listingImage" src={url} alt="Photo de l’annonce"/>:<div className="imagePlaceholder">Photo</div>}
