'use client';
import { FormEvent, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';
import { isUniverseId, universeFields, universeMap } from '@/lib/universes';
import type { UniverseId } from '@/types/winswi';

export default function PublishPage(){
 const {universe:raw}=useParams<{universe:string}>(); const universe=raw as UniverseId; const router=useRouter(); const meta=isUniverseId(universe)?universeMap[universe]:null; const fields=useMemo(()=>meta?universeFields[universe]:[],[meta,universe]);
 const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [wilaya,setWilaya]=useState(''); const [commune,setCommune]=useState(''); const [price,setPrice]=useState(''); const [values,setValues]=useState<Record<string,unknown>>({}); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 if(!meta)return <main className="wrap"><div className="notice error">Univers inconnu.</div></main>;
 const set=(k:string,v:unknown)=>setValues(x=>({...x,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/listings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({universe,title,description,wilaya,commune,location:[commune,wilaya].filter(Boolean).join(', '),price:price?Number(price):undefined,metadata:values})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Publication impossible.');router.push(universe==='immo'?`/immowin/${d.data.id}`:`/universes/${universe}`);}catch(e){setError(e instanceof Error?e.message:'Erreur.')}finally{setBusy(false)}}
 return <main className="wrap"><header className="header"><div><div className="brand">WinsWi · {meta.name}</div><div className="tag">Nouvelle annonce</div></div><Link className="btn secondary" href={`/universes/${universe}`}>Retour</Link></header><section className="card formCard"><h1>Publier dans {meta.name}</h1><form onSubmit={submit} className="authForm"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Titre de l'annonce"/><textarea required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Décrivez votre offre…"/><div className="formGrid"><input value={wilaya} onChange={e=>setWilaya(e.target.value)} placeholder="Wilaya"/><input value={commune} onChange={e=>setCommune(e.target.value)} placeholder="Commune"/><input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Prix DZD (facultatif)"/></div><div className="formGrid">{fields.map(f=><label key={f.key}>{f.label}{f.type==='select'?<select value={String(values[f.key]??'')} onChange={e=>set(f.key,e.target.value)}><option value="">Choisir…</option>{f.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>:f.type==='boolean'?<input type="checkbox" checked={Boolean(values[f.key])} onChange={e=>set(f.key,e.target.checked)}/>:<input type={f.type==='number'?'number':'text'} value={String(values[f.key]??'')} onChange={e=>set(f.key,f.type==='number'?(e.target.value?Number(e.target.value):''):e.target.value)} />}</label>)}</div>{error&&<div className="notice error">{error}</div>}<button className="btn" disabled={busy}>{busy?'Publication…':'Publier'}</button></form></section></main>;
}
