'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { universes } from '@/lib/data';
import type { AIResponse, Listing } from '@/types/winswi';
export default function Home(){
 const [universe,setUniverse]=useState(''),[query,setQuery]=useState(''),[items,setItems]=useState<Listing[]>([]),[question,setQuestion]=useState(''),[answer,setAnswer]=useState<AIResponse|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){try{const p=new URLSearchParams();if(universe)p.set('universe',universe);if(query)p.set('q',query);const r=await fetch(`/api/listings?${p}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.data||[])}catch(e){setError(e instanceof Error?e.message:'Erreur') }} useEffect(()=>{void load()},[universe]);
 async function ask(){if(!question.trim())return;setBusy(true);setError('');try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:question})});const d=await r.json();if(!r.ok)throw Error(d.error);setAnswer(d);if(d.results)setItems(d.results);if(d.universe)setUniverse(d.universe)}catch(e){setError(e instanceof Error?e.message:'Erreur IA')}finally{setBusy(false)}}
 return <main className="home-screen"><section className="hero-panel"><div className="hero-copy"><span className="eyebrow">🌍 THE GLOBAL SUPER APP</span><h1>Tout ce que vous cherchez.<br/><em>Un seul compagnon.</em></h1><p>12 univers : immobilier, auto, emploi, commerce, construction, agriculture, voyage, éducation, santé, sport, food et livraison — avec WinsWi AI au centre.</p><div className="hero-actions"><Link href="/auth/sign-up" className="gold-btn">Créer un compte</Link><Link href="/auth/sign-in" className="outline-btn">Connexion</Link></div></div><div className="hero-ai-card"><div className="hero-orb">✦</div><span>WINSWI AI</span><strong>« Que puis-je faire pour vous ? »</strong><small>Texte ou voix · FR · AR · EN</small></div></section>
 <section className="universe-section"><div className="section-title"><div><span className="eyebrow">EXPLOREZ WINSWI</span><h2>Vos univers</h2></div><Link href="/demandes" className="text-link">Mes demandes →</Link></div><div className="universe-grid">{universes.map(x=><button key={x.id} onClick={()=>setUniverse(x.id)} className={`universe-tile ${universe===x.id?'active':''}`}><span>{x.icon}</span><strong>{x.name}</strong><small>{x.desc}</small></button>)}</div></section>
 <section className="search-panel"><div className="search-title"><span className="eyebrow">RECHERCHE INTELLIGENTE</span><h2>Que recherchez-vous ?</h2></div><div className="search-line"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load()} placeholder="F3 à Mostaganem, Toyota Corolla, emploi développeur…"/><button className="gold-btn" onClick={()=>void load()}>Rechercher</button></div></section>
 {error&&<div className="notice error">{error}</div>}
 <section className="results-section"><div className="section-title"><div><span className="eyebrow">MATCHING</span><h2>{universe?universes.find(x=>x.id===universe)?.name:'Opportunités pour vous'}</h2></div><span className="result-count">{items.length} résultat(s)</span></div><div className="listing-grid">{items.map(x=><article className="listing-card" key={x.id} onClick={()=>window.location.href=x.universe==='immo'?`/immowin/${x.id}`:`/annonce/${x.id}`}><div className="listing-image"><span>{x.universe==='immo'?'🏠':x.universe==='auto'?'🚗':x.universe==='job'?'💼':'✦'}</span></div><div className="listing-body"><span className="listing-meta">{x.location||'Algérie'} · {x.universe}</span><h3>{x.title}</h3><p>{x.description}</p>{x.price!==undefined&&<strong className="listing-price">{x.price.toLocaleString('fr-DZ')} {x.currency}</strong>}</div></article>)}</div></section>
 <section className="ai-command"><div><span className="eyebrow">WINSWI AI</span><h2>Parlez-lui comme à un assistant.</h2><p>« Trouve-moi une maison à Mostaganem avec 4 chambres et un budget de 3 milliards. »</p></div><div className="ai-command-box"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void ask()} placeholder="Écrivez votre demande…"/><button className="gold-btn" onClick={()=>void ask()} disabled={busy}>{busy?'…':'Demander'}</button>{answer&&<div className="ai-answer">{answer.text}</div>}</div></section>
 <footer className="footer">WinsWi · Algérie d’abord · 12 univers · IA native · International</footer></main>
}
