'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
type Lead={id:string;name:string;phone?:string;email?:string;stage:string;score:number;notes:string;listing_id?:string};
const stages=['new','contacted','qualified','appointment','visit','negotiation','won','lost'];
const labels:{[k:string]:string}={new:'Nouveau',contacted:'Contacté',qualified:'Qualifié',appointment:'Rendez-vous',visit:'Visite',negotiation:'Négociation',won:'Gagné',lost:'Perdu'};
export default function ProPage(){const [leads,setLeads]=useState<Lead[]>([]),[name,setName]=useState(''),[phone,setPhone]=useState(''),[stage,setStage]=useState('new'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/crm/leads',{cache:'no-store'});const d=await r.json();if(r.ok)setLeads(d.data||[]);else setError(d.error||'Connexion requise.')} useEffect(()=>{void load()},[]);
 const counts=useMemo(()=>Object.fromEntries(stages.map(s=>[s,leads.filter(l=>l.stage===s).length])),[leads]);
 async function add(){if(!name.trim())return;setBusy(true);const r=await fetch('/api/crm/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,phone,stage})});const d=await r.json();if(r.ok){setName('');setPhone('');await load()}else setError(d.error||'Erreur');setBusy(false)}
 async function update(id:string,value:string){await fetch('/api/crm/leads',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,stage:value})});await load()}
 return <main className="page-wrap pro-page"><section className="screen-hero pro-hero"><div><span className="eyebrow">IMMOWIN PRO</span><h1>Agence · Promoteur · CRM</h1><p>Centralisez vos prospects, vos biens et votre suivi commercial dans WinsWi.</p></div><Link className="gold-btn" href="/publier/immo">+ Nouveau bien</Link></section><div className="metric-row">{[['Prospects',leads.length],['Nouveaux',counts.new||0],['Qualifiés',counts.qualified||0],['Gagnés',counts.won||0]].map(([a,b])=><div className="metric-card" key={String(a)}><span>{a}</span><strong>{b}</strong></div>)}</div><section className="pro-grid"><div className="dark-card"><div className="section-title"><div><span className="eyebrow">CRM</span><h2>Ajouter un prospect</h2></div></div><div className="formGrid"><input placeholder="Nom / entreprise" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Téléphone" value={phone} onChange={e=>setPhone(e.target.value)}/><select value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div><button className="gold-btn full" disabled={busy} onClick={add}>{busy?'Enregistrement…':'Ajouter au CRM'}</button>{error&&<div className="notice error">{error}</div>}</div><div className="dark-card"><span className="eyebrow">PIPELINE</span><h2>Suivi commercial</h2><div className="pipeline">{stages.map(s=><div className="pipeline-col" key={s}><div className="pipeline-head"><span>{labels[s]}</span><b>{counts[s]||0}</b></div>{leads.filter(l=>l.stage===s).slice(0,8).map(l=><div className="lead-card" key={l.id}><strong>{l.name}</strong><span>{l.phone||'Sans téléphone'}</span><small>Score {l.score}/100</small><select value={l.stage} onChange={e=>update(l.id,e.target.value)}>{stages.map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></div>)}</div>)}</div></div></section><section className="dark-card professional-features"><span className="eyebrow">ESPACE PROFESSIONNEL</span><h2>Une vraie vitrine métier</h2><div className="feature-grid"><div><b>Agence</b><span>Profil public, équipe, portefeuille, demandes et statistiques.</span></div><div><b>Promoteur</b><span>Programmes immobiliers, lots, disponibilités et leads.</span></div><div><b>CRM</b><span>Pipeline, notes, activités, rendez-vous et historique.</span></div><div><b>Acquisition</b><span>Campagnes publicitaires et mesure des conversions.</span></div></div><Link className="outline-btn" href="/publicite">Créer une campagne publicitaire</Link></section></main>}
